### ISSUE TITLE
Not able to pull content json files from server

### ISSUE THREAD

**Issue by Droid567492** [ItsJokerZz/FPKGi#10]
I've set up a simple http-server using node.js. It serves both the pkg files and the content jsons. Sadly after entering the url from which the app could pull the newest content jsons in the config.json file, nothing happens. I enabled populating from web, but when I reload the jsons nothing happens. Relaunching the app didn't help. I don't really know what could be the issue, since if I copy the content jsons over manually, every pkg shows up, and downloads work as they should.

**Comment by qqshfox** [comment]
0.87 doesn't work for me. Downgrading to 0.86 solved issue for me.

**Comment by gabberhq** [comment]
same there. I uploaded the json files manually to the folder.

The download works but not the installation. The pkg files remains.

**Comment by ItsJokerZz** [comment]
@qqshfox The issue is getting resolved as I type this now, and for @Droid567492 which version are you using? Those issues should've been resolved with the latest (`0.87`) but I'll reply to this once the next version is out and ready, then please update via your prefered method. Sorry for the inconvenience, most testing has only been done by mself unfortunately. If possible please join my server and  I can provide test builds to further better the app. Thank you guys and sorry again.

**Comment by Droid567492** [comment]
I am on version 0.87. Sadly didn't have time yet to test whether the issue exists on the earlier version mentioned above too. Also, no need for apologising, as you're doing this project completely for free. I would love to help testing the dev builds and keep this project rolling. I will join your server as soon as I get home. Thank you for your time you put in this project. 🫶

**Comment by ItsJokerZz** [comment]
Okay thank you for the info, I've since fixed it and should be out shortly! :D Much love and I appreciate it.

**Comment by gabberhq** [comment]
No probz to do some additional tests

**Comment by qqshfox** [comment]
> 0.87 doesn't work for me. Downgrading to 0.86 solved issue for me.

Actually 0.86 doesn't download files for me. It can pull the json files from a remote server but it isn't able to download it.

Downgrading to 0.81 makes it able to pull the json files from remote and download.

**Comment by ItsJokerZz** [comment]
0.86 and 0.87 have issues with populating and download/installing content currenlty. If you'd like I can provide a test build for now but should be fixed this afternoon EST time, been trying to debug a strange issue one user reported, they were having issues with 0.86 and 87 not loading any content and failing to check for updates due to sandbox issues on multiple consoles on all different FW but others didnt have the issue at all! Sorry about this, been going nuts to resolve it without removing the update system entirely.
The latest 0.87.1 should resolve these issues.

**Comment by ItsJokerZz** [comment]
Please try this: http://temp.sh/OHMCw/FPKGi_v0.87.1-nightly_build_82.pkg this should resolve all previous issues and report back either here or perferably the Discord server if possible, and from there we can do more debugging and testing for future builds @qqshfox. Sorry for the inconvenience and thanks for your report! This addresses the following:
```
Fixed populate via web not working (didn't load data)
Fixed not able to install any content after last update 
Fixed the background image showing white, if file is missing
Improved the UI interaction throughout the app all-around
Resolved not updating in UI content updated with app open
```
![Image](https://github.com/user-attachments/assets/112bbe50-c620-4437-8a94-223a118c3075)

**Comment by Gowapo18** [comment]
Still seems to not work on mine. Not sure what I’m doing wrong.

Edit: I hypothesize it’s my config file but I’m not really sure because it’s supposed to generate a new one when launching for the first time.

Edit 2: It populates now but I still can’t download from my server. It doesn’t seem to work on WiFi which I’m using.

**Comment by gabberhq** [comment]
can't download, got a message  : " Maximum download limit reached "

**Comment by ItsJokerZz** [comment]
The latest available version has several issues related to downloading and installing but I'm resolving it all, and should be out today. @Gowapo18

**Comment by ItsJokerZz** [comment]
@gabberhq That seems to be an issue with whatever third-party source you're using. Nothing in the code would throw that and there's no real way to handle / workaround that.

**Comment by gabberhq** [comment]
I got this message when trying to DL :  http://temp.sh/OHMCw/FPKGi_v0.87.1-nightly_build_82.pkg

**Comment by ItsJokerZz** [comment]
Oh, well yea.. its a temp file, new branch soon to help with stuff like this

**Comment by ItsJokerZz** [comment]
New nightly pre-release is out, I'm gonna close these and other related issues. Thank you and please open another if needed.
